services:
  postgres:
    container_name: nestjs-playground-postgres
    image: postgres:15.12
    ports:
      - '5432:5432'
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env

  pgadmin:
    container_name: nestjs-kysely-pgadmin
    image: dpage/pgadmin4:7.5
    networks:
      - postgres
    ports:
      - '8080:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env

networks:
  postgres:
    driver: bridge
